export const FETCH_TRANSACTIONS_START = 'FETCH_TRANSACTIONS_START';
export const FETCH_TRANSACTIONS_SUCCESS = 'FETCH_TRANSACTIONS_SUCCESS';
export const FETCH_TRANSACTIONS_FAILURE = 'FETCH_TRANSACTIONS_FAILURE';

export const TRANSACTION_OP_START = 'TRANSACTION_OP_START';
export const TRANSACTION_OP_END = 'TRANSACTION_OP_END';

export const ADD_TRANSACTION_SUCCESS = 'ADD_TRANSACTION_SUCCESS';
export const EDIT_TRANSACTION_SUCCESS = 'EDIT_TRANSACTION_SUCCESS';
export const DELETE_TRANSACTION_SUCCESS = 'DELETE_TRANSACTION_SUCCESS';

export const SET_ROLE = 'SET_ROLE';
export const TOGGLE_THEME = 'TOGGLE_THEME';
export const SET_FILTERS = 'SET_FILTERS';
export const SET_GROUP_BY = 'SET_GROUP_BY';
export const RESET_FILTERS = 'RESET_FILTERS';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';